name: flutter_datawedge_plus
description: A Flutter plugin communicate with DataWedge scanners.
version: 0.0.5
homepage: https://github.com/circuskitchens/flutter_datawedge_plus
repository: https://github.com/circuskitchens/flutter_datawedge_plus

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.circuskitchens.flutter_datawedge_plus
        pluginClass: FlutterDatawedgePlugin
