name: flutter_datawedge
description: A Flutter package to communicate with Zebra DataWedge scanners using the DataWedge Intent API
version: 1.0.0
homepage: https://github.com/circuskitchens/flutter_datawedge
repository: https://github.com/circuskitchens/flutter_datawedge

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.circuskitchens.flutter_datawedge
        pluginClass: FlutterDatawedgePlugin
