name: flutter_datawedge
description: A Flutter plugin communicate with DataWedge scanners.
version: 0.0.4
homepage: https://github.com/rafaeljustinox/flutter_datawedge
repository: https://github.com/rafaeljustinox/flutter_datawedge

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.3.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.justino.flutter_datawedge
        pluginClass: FlutterDatawedgePlugin
