name: flutter_datawedge_plus
description: A Flutter plugin communicate with DataWedge scanners.
version: 1.0.0
homepage: https://github.com/circuskitchens/flutter_datawedge_plus
repository: https://github.com/circuskitchens/flutter_datawedge_plus
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.3.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.circuskitchens.flutter_datawedge_plus
        pluginClass: FlutterDatawedgePlugin
